### ISSUE TITLE
Navigation wraps badly at certain narrownesses

### ISSUE THREAD

**Issue by frabcus** [frabcus/mpcv#49]
At narrow widths on some devices (and on my Firefox on a Mac if I zoom size in 1), I get this horrid wrapping on the front page.

![image](https://cloud.githubusercontent.com/assets/10153/6860010/43c51b9e-d419-11e4-92a7-db0b022bae3a.png)

Not only is it horrid, but the top nav then overlaps the text. I think really the nav should be tolerant enough that if something does make it wrap it copes. And in this case, it somehow shouldn't wrap (not sure how!).

**Comment by frabcus** [comment]
This thread is related http://stackoverflow.com/questions/11124777/twitter-bootstrap-navbar-fixed-top-overlapping-site.

I have this CSS for what it is talking about:

``` css
.contentwrap {
    padding-top: 22px;
}

@media (min-width: 768px) {
  .contentwrap {
      padding-top: 42px;
  }
}

@media (min-width: 992px) {
  .sidebarwrap {
    padding-top: 42px;
  }
}
```
